# Directory configuration holding various paths used in the script.
directories:
  # Base paths for easier modification.
  base_path: "/global/cfs/cdirs/desi/survey/catalogs/Y1/LSS/iron/LSScats/v0.6/blinded/"
   
  # Directory paths related to pk and xi data.
  pk: "/global/cfs/cdirs/desi/survey/catalogs/Y1/LSS/iron/LSScats/v0.6/blinded/pk/" #pay attention to the last slash
  xi: "/global/cfs/cdirs/desi/survey/catalogs/Y1/LSS/iron/LSScats/v0.6/blinded/xi/"

  # Paths to external tools used in the script.
  external_tools:  
    # Path to the directory where the covariance matrix data is stored.
    thecov: "/global/cfs/cdirs/desi/survey/catalogs/Y1/LSS/iron/LSScats/v0.6/blinded/pk/covariances/"
    # Path to the RascalC tool directory.
    rascal: "/global/cfs/cdirs/desi/users/mrash/RascalC/Y1/blinded/v0.6/"
