# Directory configuration holding various paths used in the script.
directories:
  # Paths related to catalog directories.
  catalogs:
    # Main directory holding unblinded catalog data.
    main: "/global/cfs/cdirs/desi/survey/catalogs/main/mocks/FirstGenMocks/AbacusSummit/Y1/mock1/LSScats"
    
    # List of directories for different blind cosmology test cases.
    blind_cosmology_tests:
      # Directory for the test case with specified w0 and wa parameters.
      - "/global/cfs/cdirs/desi/users/uendert/desi_blinding/blind_cosmology/test_w0-0.9040043101843285_wa0.025634205416364297"
      - "/global/cfs/cdirs/desi/users/uendert/desi_blinding/blind_cosmology/test_w0-0.9057030601797708_wa-0.6831142329608426"
      - "/global/cfs/cdirs/desi/users/uendert/desi_blinding/blind_cosmology/test_w0-0.970439944958287_wa-0.507777992481059" 
      - "/global/cfs/cdirs/desi/users/uendert/desi_blinding/blind_cosmology/test_w0-0.996229742129104_wa0.28930866494014884"
      - "/global/cfs/cdirs/desi/users/uendert/desi_blinding/blind_cosmology/test_w0-1.0485430984101343_wa0.14015686872763022"
      - "/global/cfs/cdirs/desi/users/uendert/desi_blinding/blind_cosmology/test_w0-1.106392086529483_wa0.45478607672455995"
      - "/global/cfs/cdirs/desi/users/uendert/desi_blinding/blind_cosmology/test_w0-1.1616966626392298_wa0.3746115553255438"
      - "/global/cfs/cdirs/desi/users/uendert/desi_blinding/blind_cosmology/test_w0-1.233469858595847_wa0.7658531629974685"

  # Directory paths related to pk_xi data.
  pk_xi:
    # Directory where the unblinded pk_xi data is stored.
    unblinded: "/global/cfs/cdirs/desi/users/uendert/desi_blinding/blind_cosmology/unblinded/pk_xi/" #pay attention to the last slash

  # Paths to external tools used in the script.
  external_tools:  
    # Path to the directory where the covariance matrix data is stored.
    thecov: "/global/cfs/cdirs/desi/survey/catalogs/main/mocks/FirstGenMocks/AbacusSummit/Y1/mock1/LSScats/blinded/jmena/pk_xi_measurements/CovPk/"

    # Path to the RascalC tool directory.
    rascal: "/global/cfs/cdirs/desi/users/mrash/RascalC/AbacusSummit/CutSky/Y1-blinding/"
